name: GhPage deploy - main
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    env:
      CI: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup pnpm as package manager
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Setup Node v.${{ matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version}}
          cache: pnpm
      - name: "Install dependencies"
        run: pnpm install --frozen-lockfile
      - name: "Run app tests"
        run: pnpm run test --detectOpenHandles
      - name: "Build application"
        run: pnpm run build --if-present
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
